apiVersion: v1
kind: Service
metadata:
  name: eks-lab-service
  namespace: lab-env
  labels:
    app: eks-lab-app
spec:
  selector:
    app: eks-lab-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

