apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-lab-deployment
  namespace: lab-env
  labels:
    app: eks-lab-app
spec:
  replicas: 15
  selector:
    matchLabels:
      app: eks-lab-app
  template:
    metadata:
      labels:
        app: eks-lab-app
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.23
        ports:
        - name: http
          containerPort: 80
